### ISSUE TITLE
Split eosio.system_tests.cpp so tests can run in parallel in CICD to reduce overall CICD time

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/reference-contracts#102]
Currently `eosio.system_tests.cpp` is 5,921 lines long and takes 5 minutes to run in CICD libtester (https://github.com/AntelopeIO/spring/actions/runs/9468157289/job/26085190747#step:16:984). The next longest test is `eosio_system_finalizer_key_unit_test` which is about 1 minute. We can split `eosio.system_tests.cpp` into multiple files (tests) and make each of them run around 1 minute; those tests can run in parallel with other tests. This will reduce libtester running time to about 1 minute, a huge saving without risks, plus smaller files to reduce compilation time if changes are in one small file.

**Comment by heifner** [comment]
In addition many of these test produce a large number of blocks for no reason. See changes in https://github.com/AntelopeIO/spring/pull/273
For example:
https://github.com/AntelopeIO/spring/pull/273/files#diff-772ea8af1ac7513dba7209d87abdd10757824ab895a16b9f174f740c17232508L35
