### ISSUE TITLE
Order of install contracts

### ISSUE THREAD

**Issue by riotom** [AntelopeIO/reference-contracts#18]
trouble with install eosio.system

    cleos     main.cpp:700                  print_result         ] soft_except->to_detail_string(): 3070003 
    wasm_serialization_error: Serialization Error Processing WASM
    env.set_parameters_packed unresolveable
        {"module":"env","fn":"set_parameters_packed"}
        nodeos  eos-vm.cpp:77 validate
    pending console output:
        {"console":""}
        nodeos  apply_context.cpp:124 exec_one

notning exactly docs with it.

**Comment by dacom-dark-sun** [comment]
The same problem. Anyone can explain how to fix it?

**Comment by heifner** [comment]
You have to activate protocol features before setting the reference system contract. See how it is done here: https://github.com/AntelopeIO/leap/blob/main/tutorials/bios-boot-tutorial/bios-boot-tutorial.py#L297

**Comment by dacom-dark-sun** [comment]
> You have to activate protocol features before setting the reference system contract. See how it is done here: https://github.com/AntelopeIO/leap/blob/main/tutorials/bios-boot-tutorial/bios-boot-tutorial.py#L297

Thanks a lot

**Comment by ericpassmore** [comment]
Issue resolved
