### ISSUE TITLE
Remove dependence on deferred transactions in reference contracts

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/reference-contracts#8]
After https://github.com/AntelopeIO/reference-contracts/issues/7 is complete, only the core contract should have deferred transactions used in a couple of places (unstaking refund and name bid refund). But already have ways to claim the refunds in case the deferred transactions fail. So removing the deferred transaction dependency in the core contract can be as simple as removing the lines that schedule the redundant deferred transaction.

Note however this will have the impact of always requires users to take another explicit action (which requires signing a new transaction) to actually claim the refund whereas now the process does usually happen automatically. To make this process less burdensome, we may wish to explore changes to make it possible for anyone to automate the refund claiming on behalf of the user. This may simply involving adjusting the authorization required for the `refund` action so that anyone can claim a refund on behalf of a user rather than only the user who is owed the refund. However, due to the user impact of this change, we may still wish to further consider the approach we take here before removing the deferred transaction support in the core contract.

**Comment by ericpassmore** [comment]
closed with merge of PR #29
