### ISSUE TITLE
Invalid Signature Unable to Download Spring

### ISSUE THREAD

**Issue by ericpassmore** [AntelopeIO/reference-contracts#97]
Run AntelopeIO/asset-artifact-download-action@v3
  with:
    owner: AntelopeIO
    repo: spring
    file: spring-dev.*ubuntu[2](https://github.com/AntelopeIO/reference-contracts/actions/runs/9296673519/job/25585552195?pr=96#step:4:2)2\.04_amd64.deb
    target: main
    prereleases: false
    artifact-name: spring-dev-ubuntu22-amd64
    container-package: experimental-binaries
    token: ***
    fail-on-missing-target: true
    wait-for-exact-target: false
Downloaded spring-dev_1.0.0-dev-ubuntu22.04_amd64.deb from e[3](https://github.com/AntelopeIO/reference-contracts/actions/runs/9296673519/job/25585552195?pr=96#step:4:3)da612c0c5efcc2e213c3501fdd08d611032[4](https://github.com/AntelopeIO/reference-contracts/actions/runs/9296673519/job/25585552195?pr=96#step:4:4)da artifact spring-dev-ubuntu22-amd64
Error: invalid signature: 0x1da0[6](https://github.com/AntelopeIO/reference-contracts/actions/runs/9296673519/job/25585552195?pr=96#step:4:6)171

**Comment by ericpassmore** [comment]
Is this still an ongoing issue?

**Comment by spoonincode** [comment]
This was resolved with AntelopeIO/asset-artifact-download-action@589a841
